[2025-01-16T20:05:38.112+0000] {processor.py:186} INFO - Started process (PID=8381) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:05:38.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:05:38.114+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:05:38.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:05:38.128+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:05:38.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:05:38.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:05:38.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.040 seconds
[2025-01-16T20:06:08.437+0000] {processor.py:186} INFO - Started process (PID=8442) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:06:08.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:06:08.440+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:06:08.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:06:08.454+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:06:08.453+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:06:08.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:06:08.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:06:38.702+0000] {processor.py:186} INFO - Started process (PID=8504) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:06:38.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:06:38.704+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:06:38.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:06:38.720+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:06:38.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:06:38.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:06:38.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:07:09.214+0000] {processor.py:186} INFO - Started process (PID=8564) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:07:09.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:07:09.217+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:07:09.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:07:09.228+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:07:09.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:07:09.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:07:09.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-16T20:07:39.434+0000] {processor.py:186} INFO - Started process (PID=8624) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:07:39.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:07:39.436+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:07:39.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:07:39.448+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:07:39.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:07:39.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:07:39.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-16T20:08:10.368+0000] {processor.py:186} INFO - Started process (PID=8688) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:08:10.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:08:10.370+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:08:10.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:08:10.383+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:08:10.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:08:10.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:08:10.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-16T20:08:40.628+0000] {processor.py:186} INFO - Started process (PID=8754) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:08:40.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:08:40.630+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:08:40.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:08:40.643+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:08:40.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:08:40.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:08:40.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:09:11.242+0000] {processor.py:186} INFO - Started process (PID=8820) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:09:11.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:09:11.245+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:09:11.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:09:11.259+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:09:11.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:09:11.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:09:11.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.056 seconds
[2025-01-16T20:09:41.673+0000] {processor.py:186} INFO - Started process (PID=8886) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:09:41.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:09:41.676+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:09:41.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:09:41.689+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:09:41.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:09:41.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:09:41.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T20:10:11.914+0000] {processor.py:186} INFO - Started process (PID=8952) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:10:11.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:10:11.917+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:10:11.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:10:11.934+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:10:11.932+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:10:11.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:10:11.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-16T20:10:42.807+0000] {processor.py:186} INFO - Started process (PID=9018) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:10:42.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:10:42.809+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:10:42.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:10:42.822+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:10:42.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:10:42.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:10:42.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:11:13.564+0000] {processor.py:186} INFO - Started process (PID=9084) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:11:13.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:11:13.566+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:11:13.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:11:13.580+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:11:13.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:11:13.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:11:13.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-16T20:11:44.175+0000] {processor.py:186} INFO - Started process (PID=9150) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:11:44.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:11:44.178+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:11:44.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:11:44.190+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:11:44.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:11:44.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:11:44.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:12:14.475+0000] {processor.py:186} INFO - Started process (PID=9216) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:12:14.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:12:14.478+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:12:14.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:12:14.489+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:12:14.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:12:14.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:12:14.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:12:45.337+0000] {processor.py:186} INFO - Started process (PID=9282) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:12:45.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:12:45.340+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:12:45.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:12:45.357+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:12:45.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:12:45.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:12:45.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.060 seconds
[2025-01-16T20:13:15.680+0000] {processor.py:186} INFO - Started process (PID=9348) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:13:15.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:13:15.683+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:13:15.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:13:15.696+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:13:15.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:13:15.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:13:15.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-16T20:13:46.008+0000] {processor.py:186} INFO - Started process (PID=9414) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:13:46.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:13:46.010+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:13:46.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:13:46.025+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:13:46.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:13:46.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:13:46.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-16T20:14:16.515+0000] {processor.py:186} INFO - Started process (PID=9480) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:14:16.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:14:16.518+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:14:16.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:14:16.534+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:14:16.533+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:14:16.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:14:16.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:14:47.372+0000] {processor.py:186} INFO - Started process (PID=9546) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:14:47.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:14:47.375+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:14:47.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:14:47.394+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:14:47.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:14:47.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:14:47.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.059 seconds
[2025-01-16T20:15:17.589+0000] {processor.py:186} INFO - Started process (PID=9612) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:15:17.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:15:17.591+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:15:17.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:15:17.607+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:15:17.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:15:17.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:15:17.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.051 seconds
[2025-01-16T20:15:48.478+0000] {processor.py:186} INFO - Started process (PID=9679) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:15:48.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:15:48.481+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:15:48.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:15:48.493+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:15:48.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:15:48.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:15:48.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:16:18.868+0000] {processor.py:186} INFO - Started process (PID=9746) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:16:18.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:16:18.871+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:16:18.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:16:18.883+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:16:18.882+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:16:18.884+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:16:18.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:16:49.335+0000] {processor.py:186} INFO - Started process (PID=9813) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:16:49.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:16:49.337+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:16:49.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:16:49.352+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:16:49.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:16:49.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:16:49.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.055 seconds
[2025-01-16T20:17:19.780+0000] {processor.py:186} INFO - Started process (PID=9880) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:17:19.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:17:19.785+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:17:19.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:17:19.805+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:17:19.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:17:19.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:17:19.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.060 seconds
[2025-01-16T20:17:50.511+0000] {processor.py:186} INFO - Started process (PID=9947) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:17:50.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:17:50.513+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:17:50.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:17:50.525+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:17:50.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:17:50.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:17:50.553+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:18:20.665+0000] {processor.py:186} INFO - Started process (PID=10014) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:18:20.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:18:20.667+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:18:20.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:18:20.680+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:18:20.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:18:20.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:18:20.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:18:51.328+0000] {processor.py:186} INFO - Started process (PID=10081) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:18:51.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:18:51.331+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:18:51.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:18:51.344+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:18:51.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:18:51.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:18:51.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:19:21.577+0000] {processor.py:186} INFO - Started process (PID=10148) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:19:21.578+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:19:21.580+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:19:21.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:19:21.594+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:19:21.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:19:21.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:19:21.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:19:52.019+0000] {processor.py:186} INFO - Started process (PID=10215) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:19:52.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:19:52.022+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:19:52.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:19:52.037+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:19:52.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:19:52.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:19:52.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-16T20:20:22.324+0000] {processor.py:186} INFO - Started process (PID=10282) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:20:22.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:20:22.325+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:20:22.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:20:22.338+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:20:22.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:20:22.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:20:22.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:20:52.601+0000] {processor.py:186} INFO - Started process (PID=10349) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:20:52.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:20:52.604+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:20:52.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:20:52.621+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:20:52.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:20:52.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:20:52.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.057 seconds
[2025-01-16T20:21:23.033+0000] {processor.py:186} INFO - Started process (PID=10417) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:21:23.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:21:23.038+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:21:23.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:21:23.051+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:21:23.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:21:23.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:21:23.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:21:53.352+0000] {processor.py:186} INFO - Started process (PID=10484) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:21:53.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:21:53.354+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:21:53.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:21:53.370+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:21:53.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:21:53.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:21:53.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.058 seconds
[2025-01-16T20:22:23.559+0000] {processor.py:186} INFO - Started process (PID=10551) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:22:23.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:22:23.562+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:22:23.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:22:23.576+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:22:23.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:22:23.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:22:23.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.060 seconds
[2025-01-16T20:22:54.041+0000] {processor.py:186} INFO - Started process (PID=10618) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:22:54.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:22:54.043+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:22:54.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:22:54.057+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:22:54.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:22:54.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:22:54.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.054 seconds
[2025-01-16T20:23:24.430+0000] {processor.py:186} INFO - Started process (PID=10685) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:23:24.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:23:24.433+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:23:24.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:23:24.446+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:23:24.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:23:24.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:23:24.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:23:54.530+0000] {processor.py:186} INFO - Started process (PID=10752) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:23:54.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:23:54.532+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:23:54.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:23:54.543+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:23:54.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:23:54.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:23:54.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:24:25.366+0000] {processor.py:186} INFO - Started process (PID=10818) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:24:25.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:24:25.370+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:24:25.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:24:25.385+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:24:25.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:24:25.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:24:25.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.055 seconds
[2025-01-16T20:24:56.209+0000] {processor.py:186} INFO - Started process (PID=10885) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:24:56.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:24:56.212+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:24:56.211+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:24:56.229+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:24:56.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:24:56.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:24:56.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.054 seconds
[2025-01-16T20:25:27.047+0000] {processor.py:186} INFO - Started process (PID=10952) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:25:27.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:25:27.051+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:25:27.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:25:27.086+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:25:27.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:25:27.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:25:27.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.086 seconds
[2025-01-16T20:25:57.386+0000] {processor.py:186} INFO - Started process (PID=11019) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:25:57.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:25:57.389+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:25:57.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:25:57.408+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:25:57.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:25:57.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:25:57.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.065 seconds
[2025-01-16T20:26:27.906+0000] {processor.py:186} INFO - Started process (PID=11073) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:26:27.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:26:27.909+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:26:27.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:26:27.930+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:26:27.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:26:27.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:26:27.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.065 seconds
[2025-01-16T20:26:58.805+0000] {processor.py:186} INFO - Started process (PID=11134) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:26:58.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:26:58.809+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:26:58.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:26:58.827+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:26:58.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:26:58.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:26:58.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.077 seconds
[2025-01-16T20:27:29.119+0000] {processor.py:186} INFO - Started process (PID=11194) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:27:29.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:27:29.122+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:27:29.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:27:29.143+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:27:29.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:27:29.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:27:29.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.063 seconds
[2025-01-16T20:27:59.291+0000] {processor.py:186} INFO - Started process (PID=11261) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:27:59.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:27:59.295+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:27:59.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:27:59.320+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:27:59.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:27:59.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:27:59.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.077 seconds
[2025-01-16T20:28:30.109+0000] {processor.py:186} INFO - Started process (PID=11326) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:28:30.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:28:30.111+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:28:30.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:28:30.129+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:28:30.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:28:30.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:28:30.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.053 seconds
[2025-01-16T20:29:00.552+0000] {processor.py:186} INFO - Started process (PID=11386) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:29:00.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:29:00.557+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:29:00.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:29:00.604+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:29:00.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:29:00.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:29:00.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.094 seconds
[2025-01-16T20:29:31.438+0000] {processor.py:186} INFO - Started process (PID=11460) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:29:31.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:29:31.442+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:29:31.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:29:31.463+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:29:31.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:29:31.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:29:31.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.072 seconds
[2025-01-16T20:30:02.204+0000] {processor.py:186} INFO - Started process (PID=11527) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:30:02.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:30:02.207+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:30:02.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:30:02.221+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:30:02.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:30:02.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:30:02.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-16T20:30:32.776+0000] {processor.py:186} INFO - Started process (PID=11594) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:30:32.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:30:32.779+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:30:32.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:30:32.794+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:30:32.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:30:32.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:30:32.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.052 seconds
[2025-01-16T20:31:02.994+0000] {processor.py:186} INFO - Started process (PID=11661) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:31:02.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:31:02.998+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:31:02.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:31:03.010+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:31:03.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:31:03.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:31:03.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-16T20:31:33.232+0000] {processor.py:186} INFO - Started process (PID=11727) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:31:33.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:31:33.236+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:31:33.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:31:33.248+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:31:33.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:31:33.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:31:33.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-16T20:32:03.433+0000] {processor.py:186} INFO - Started process (PID=11793) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:32:03.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:32:03.436+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:32:03.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:32:03.448+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:32:03.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:32:03.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:32:03.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-16T20:32:33.856+0000] {processor.py:186} INFO - Started process (PID=11859) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:32:33.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:32:33.859+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:32:33.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:32:33.873+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:32:33.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:32:33.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:32:33.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-16T20:33:04.161+0000] {processor.py:186} INFO - Started process (PID=11925) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:33:04.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:33:04.163+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:33:04.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:33:04.178+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:33:04.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:33:04.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:33:04.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.052 seconds
[2025-01-16T20:33:34.867+0000] {processor.py:186} INFO - Started process (PID=11991) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:33:34.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:33:34.872+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:33:34.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:33:34.893+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:33:34.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:33:34.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:33:34.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.059 seconds
[2025-01-16T20:34:05.217+0000] {processor.py:186} INFO - Started process (PID=12057) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:34:05.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:34:05.220+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:34:05.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:34:05.237+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:34:05.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:34:05.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:34:05.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-16T20:34:35.415+0000] {processor.py:186} INFO - Started process (PID=12123) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:34:35.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:34:35.418+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:34:35.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:34:35.439+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:34:35.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:34:35.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:34:35.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.062 seconds
[2025-01-16T20:35:06.351+0000] {processor.py:186} INFO - Started process (PID=12189) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:35:06.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:35:06.355+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:35:06.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:35:06.371+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:35:06.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:35:06.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:35:06.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.057 seconds
[2025-01-16T20:35:36.599+0000] {processor.py:186} INFO - Started process (PID=12255) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:35:36.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:35:36.601+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:35:36.600+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:35:36.615+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:35:36.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:35:36.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:35:36.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-16T20:36:07.114+0000] {processor.py:186} INFO - Started process (PID=12321) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:36:07.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:36:07.116+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:36:07.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:36:07.133+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:36:07.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:36:07.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:36:07.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.059 seconds
[2025-01-16T20:36:37.847+0000] {processor.py:186} INFO - Started process (PID=12387) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:36:37.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:36:37.851+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:36:37.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:36:37.866+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:36:37.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:36:37.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:36:37.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.058 seconds
[2025-01-16T20:37:08.052+0000] {processor.py:186} INFO - Started process (PID=12453) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:37:08.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:37:08.060+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:37:08.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:37:08.090+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:37:08.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:37:08.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:37:08.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.068 seconds
[2025-01-16T20:37:39.119+0000] {processor.py:186} INFO - Started process (PID=12519) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:37:39.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:37:39.122+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:37:39.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:37:39.140+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:37:39.139+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:37:39.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:37:39.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.057 seconds
[2025-01-16T20:38:09.240+0000] {processor.py:186} INFO - Started process (PID=12585) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:38:09.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:38:09.243+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:38:09.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:38:09.260+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:38:09.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:38:09.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:38:09.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.058 seconds
[2025-01-16T20:38:39.978+0000] {processor.py:186} INFO - Started process (PID=12651) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:38:39.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:38:39.980+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:38:39.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:38:39.994+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:38:39.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:38:39.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:38:40.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-16T20:39:10.412+0000] {processor.py:186} INFO - Started process (PID=12717) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:39:10.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:39:10.416+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:39:10.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:39:10.437+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:39:10.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:39:10.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:39:10.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.075 seconds
[2025-01-16T20:39:40.943+0000] {processor.py:186} INFO - Started process (PID=12783) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:39:40.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:39:40.946+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:39:40.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:39:40.959+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:39:40.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:39:40.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:39:40.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-16T20:40:11.211+0000] {processor.py:186} INFO - Started process (PID=12849) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:40:11.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:40:11.214+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:40:11.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:40:11.226+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:40:11.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:40:11.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:40:11.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-16T20:40:41.508+0000] {processor.py:186} INFO - Started process (PID=12915) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:40:41.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:40:41.510+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:40:41.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:40:41.523+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:40:41.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:40:41.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:40:41.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-16T20:41:11.591+0000] {processor.py:186} INFO - Started process (PID=12981) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:41:11.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:41:11.594+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:41:11.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:41:11.607+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:41:11.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:41:11.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:41:11.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.040 seconds
[2025-01-16T20:41:41.911+0000] {processor.py:186} INFO - Started process (PID=13047) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:41:41.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:41:41.914+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:41:41.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:41:41.926+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:41:41.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:41:41.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:41:41.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:42:12.566+0000] {processor.py:186} INFO - Started process (PID=13113) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:42:12.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:42:12.570+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:42:12.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:42:12.592+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:42:12.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:42:12.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:42:12.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.054 seconds
[2025-01-16T20:42:42.664+0000] {processor.py:186} INFO - Started process (PID=13179) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:42:42.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:42:42.666+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:42:42.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:42:42.680+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:42:42.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:42:42.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:42:42.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.051 seconds
[2025-01-16T20:43:12.775+0000] {processor.py:186} INFO - Started process (PID=13245) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:43:12.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:43:12.778+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:43:12.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:43:12.791+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:43:12.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:43:12.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:43:12.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:43:43.325+0000] {processor.py:186} INFO - Started process (PID=13311) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:43:43.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:43:43.329+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:43:43.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:43:43.352+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:43:43.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:43:43.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:43:43.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.074 seconds
[2025-01-16T20:44:13.564+0000] {processor.py:186} INFO - Started process (PID=13377) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:44:13.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:44:13.567+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:44:13.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:44:13.597+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:44:13.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:44:13.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:44:13.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.085 seconds
[2025-01-16T20:44:44.589+0000] {processor.py:186} INFO - Started process (PID=13443) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:44:44.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:44:44.592+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:44:44.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:44:44.613+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:44:44.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:44:44.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:44:44.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.051 seconds
[2025-01-16T20:45:15.189+0000] {processor.py:186} INFO - Started process (PID=13510) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:45:15.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:45:15.194+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:45:15.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:45:15.239+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:45:15.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:45:15.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:45:15.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.099 seconds
[2025-01-16T20:45:45.388+0000] {processor.py:186} INFO - Started process (PID=13574) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:45:45.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:45:45.392+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:45:45.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:45:45.413+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:45:45.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:45:45.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:45:45.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.076 seconds
[2025-01-16T20:46:15.919+0000] {processor.py:186} INFO - Started process (PID=13640) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:46:15.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:46:15.921+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:46:15.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:46:15.935+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:46:15.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:46:15.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:46:15.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-16T20:46:46.935+0000] {processor.py:186} INFO - Started process (PID=13706) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:46:46.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:46:46.937+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:46:46.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:46:46.952+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:46:46.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:46:46.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:46:46.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.054 seconds
[2025-01-16T20:47:17.142+0000] {processor.py:186} INFO - Started process (PID=13764) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:47:17.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:47:17.145+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:47:17.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:47:17.170+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:47:17.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:47:17.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:47:17.194+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.060 seconds
[2025-01-16T20:47:47.687+0000] {processor.py:186} INFO - Started process (PID=13823) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:47:47.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:47:47.691+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:47:47.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:47:47.707+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:47:47.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:47:47.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:47:47.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T20:48:18.261+0000] {processor.py:186} INFO - Started process (PID=13885) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:48:18.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:48:18.264+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:48:18.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:48:18.281+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:48:18.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:48:18.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:48:18.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.061 seconds
[2025-01-16T20:48:48.646+0000] {processor.py:186} INFO - Started process (PID=13951) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:48:48.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:48:48.649+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:48:48.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:48:48.665+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:48:48.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:48:48.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:48:48.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.055 seconds
[2025-01-16T20:49:18.866+0000] {processor.py:186} INFO - Started process (PID=14017) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:49:18.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:49:18.869+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:49:18.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:49:18.882+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:49:18.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:49:18.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:49:18.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-16T20:49:49.557+0000] {processor.py:186} INFO - Started process (PID=14083) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:49:49.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:49:49.561+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:49:49.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:49:49.574+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:49:49.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:49:49.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:49:49.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.055 seconds
[2025-01-16T20:50:19.790+0000] {processor.py:186} INFO - Started process (PID=14149) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:50:19.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:50:19.793+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:50:19.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:50:19.808+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:50:19.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:50:19.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:50:19.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:50:50.357+0000] {processor.py:186} INFO - Started process (PID=14215) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:50:50.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:50:50.360+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:50:50.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:50:50.374+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:50:50.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:50:50.375+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:50:50.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.051 seconds
[2025-01-16T20:51:20.767+0000] {processor.py:186} INFO - Started process (PID=14281) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:51:20.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:51:20.771+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:51:20.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:51:20.800+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:51:20.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:51:20.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:51:20.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.081 seconds
[2025-01-16T20:51:50.976+0000] {processor.py:186} INFO - Started process (PID=14347) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:51:50.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:51:50.978+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:51:50.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:51:50.989+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:51:50.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:51:50.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:51:51.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-16T20:52:21.220+0000] {processor.py:186} INFO - Started process (PID=14413) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:52:21.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:52:21.222+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:52:21.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:52:21.233+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:52:21.232+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:52:21.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:52:21.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T20:52:51.428+0000] {processor.py:186} INFO - Started process (PID=14479) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:52:51.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:52:51.432+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:52:51.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:52:51.448+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:52:51.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:52:51.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:52:51.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.056 seconds
[2025-01-16T20:53:21.732+0000] {processor.py:186} INFO - Started process (PID=14544) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:53:21.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:53:21.735+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:53:21.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:53:21.752+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:53:21.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:53:21.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:53:21.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-16T20:53:52.299+0000] {processor.py:186} INFO - Started process (PID=14610) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:53:52.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:53:52.302+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:53:52.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:53:52.312+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:53:52.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:53:52.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:53:52.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:54:22.559+0000] {processor.py:186} INFO - Started process (PID=14676) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:54:22.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:54:22.561+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:54:22.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:54:22.574+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:54:22.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:54:22.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:54:22.590+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.036 seconds
[2025-01-16T20:54:52.813+0000] {processor.py:186} INFO - Started process (PID=14742) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:54:52.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:54:52.815+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:54:52.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:54:52.827+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:54:52.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:54:52.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:54:52.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T20:55:23.258+0000] {processor.py:186} INFO - Started process (PID=14808) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:55:23.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:55:23.260+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:55:23.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:55:23.275+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:55:23.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:55:23.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:55:23.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-16T20:55:53.733+0000] {processor.py:186} INFO - Started process (PID=14874) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:55:53.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:55:53.735+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:55:53.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:55:53.745+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:55:53.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:55:53.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:55:53.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T20:56:24.068+0000] {processor.py:186} INFO - Started process (PID=14940) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:56:24.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:56:24.070+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:56:24.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:56:24.087+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:56:24.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:56:24.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:56:24.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.052 seconds
[2025-01-16T20:56:54.230+0000] {processor.py:186} INFO - Started process (PID=15006) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:56:54.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:56:54.234+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:56:54.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:56:54.252+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:56:54.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:56:54.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:56:54.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.064 seconds
[2025-01-16T20:57:24.629+0000] {processor.py:186} INFO - Started process (PID=15072) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:57:24.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:57:24.631+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:57:24.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:57:24.644+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:57:24.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:57:24.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:57:24.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-16T20:57:54.831+0000] {processor.py:186} INFO - Started process (PID=15138) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:57:54.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:57:54.834+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:57:54.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:57:54.847+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:57:54.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:57:54.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:57:54.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-16T20:58:25.092+0000] {processor.py:186} INFO - Started process (PID=15204) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:58:25.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:58:25.094+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:58:25.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:58:25.106+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:58:25.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:58:25.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:58:25.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-16T20:58:55.670+0000] {processor.py:186} INFO - Started process (PID=15270) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:58:55.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:58:55.672+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:58:55.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:58:55.684+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:58:55.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:58:55.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:58:55.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-16T20:59:25.867+0000] {processor.py:186} INFO - Started process (PID=15336) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:59:25.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:59:25.869+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:59:25.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:59:25.880+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:59:25.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:59:25.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:59:25.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.035 seconds
[2025-01-16T20:59:56.279+0000] {processor.py:186} INFO - Started process (PID=15402) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:59:56.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T20:59:56.282+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:59:56.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:59:56.305+0000] {logging_mixin.py:190} INFO - [2025-01-16T20:59:56.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T20:59:56.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T20:59:56.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.058 seconds
[2025-01-16T21:00:26.807+0000] {processor.py:186} INFO - Started process (PID=15468) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:00:26.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:00:26.809+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:00:26.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:00:26.820+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:00:26.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:00:26.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:00:26.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T21:00:56.963+0000] {processor.py:186} INFO - Started process (PID=15535) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:00:56.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:00:56.965+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:00:56.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:00:56.979+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:00:56.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:00:56.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:00:57.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T21:01:27.393+0000] {processor.py:186} INFO - Started process (PID=15601) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:01:27.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:01:27.396+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:01:27.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:01:27.406+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:01:27.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:01:27.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:01:27.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T21:01:57.631+0000] {processor.py:186} INFO - Started process (PID=15667) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:01:57.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:01:57.633+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:01:57.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:01:57.644+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:01:57.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:01:57.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:01:57.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-16T21:02:27.819+0000] {processor.py:186} INFO - Started process (PID=15733) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:02:27.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:02:27.821+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:02:27.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:02:27.834+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:02:27.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:02:27.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:02:27.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-16T21:02:58.420+0000] {processor.py:186} INFO - Started process (PID=15799) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:02:58.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:02:58.423+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:02:58.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:02:58.436+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:02:58.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:02:58.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:02:58.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-16T21:03:28.825+0000] {processor.py:186} INFO - Started process (PID=15864) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:03:28.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:03:28.828+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:03:28.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:03:28.839+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:03:28.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:03:28.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:03:28.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-16T21:03:59.322+0000] {processor.py:186} INFO - Started process (PID=15931) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:03:59.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:03:59.325+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:03:59.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:03:59.341+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:03:59.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:03:59.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:03:59.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.056 seconds
[2025-01-16T21:04:29.843+0000] {processor.py:186} INFO - Started process (PID=15998) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:04:29.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:04:29.846+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:04:29.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:04:29.858+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:04:29.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:04:29.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:04:29.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.036 seconds
[2025-01-16T21:04:59.960+0000] {processor.py:186} INFO - Started process (PID=16064) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:04:59.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:04:59.963+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:04:59.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:04:59.974+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:04:59.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:04:59.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:04:59.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-16T21:05:30.424+0000] {processor.py:186} INFO - Started process (PID=16130) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:05:30.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:05:30.426+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:05:30.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:05:30.439+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:05:30.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:05:30.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:05:30.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-16T21:06:00.651+0000] {processor.py:186} INFO - Started process (PID=16187) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:06:00.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:06:00.654+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:06:00.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:06:00.671+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:06:00.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:06:00.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:06:00.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
[2025-01-16T21:06:31.294+0000] {processor.py:186} INFO - Started process (PID=16245) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:06:31.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:06:31.296+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:06:31.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:06:31.309+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:06:31.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:06:31.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:06:31.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.036 seconds
[2025-01-16T21:07:01.792+0000] {processor.py:186} INFO - Started process (PID=16302) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:07:01.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:07:01.795+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:07:01.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:07:01.820+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:07:01.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:07:01.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:07:01.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.056 seconds
[2025-01-16T21:07:32.452+0000] {processor.py:186} INFO - Started process (PID=16368) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:07:32.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:07:32.454+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:07:32.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:07:32.465+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:07:32.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:07:32.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:07:32.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-16T21:08:02.720+0000] {processor.py:186} INFO - Started process (PID=16434) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:08:02.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-16T21:08:02.723+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:08:02.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:08:02.739+0000] {logging_mixin.py:190} INFO - [2025-01-16T21:08:02.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 44
    task_id = 'Extract'
              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-16T21:08:02.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-16T21:08:02.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.044 seconds
