[2025-01-17T11:13:59.295+0000] {processor.py:186} INFO - Started process (PID=2032) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:13:59.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:13:59.298+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:59.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:13:59.312+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:59.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:13:59.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:13:59.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-17T11:14:29.418+0000] {processor.py:186} INFO - Started process (PID=2098) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:14:29.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:14:29.421+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:29.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:14:29.435+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:29.434+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:14:29.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:14:29.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-17T11:14:59.855+0000] {processor.py:186} INFO - Started process (PID=2164) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:14:59.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:14:59.857+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:59.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:14:59.869+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:59.869+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:14:59.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:14:59.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.045 seconds
[2025-01-17T11:15:30.095+0000] {processor.py:186} INFO - Started process (PID=2237) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:15:30.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:15:30.097+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:30.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:15:30.114+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:30.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:15:30.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:15:30.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.040 seconds
[2025-01-17T11:16:00.906+0000] {processor.py:186} INFO - Started process (PID=2304) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:16:00.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:16:00.909+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:00.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:16:00.922+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:00.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:16:00.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:16:00.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-17T11:16:31.763+0000] {processor.py:186} INFO - Started process (PID=2370) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:16:31.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:16:31.766+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:31.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:16:31.778+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:31.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:16:31.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:16:31.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-17T11:17:02.321+0000] {processor.py:186} INFO - Started process (PID=2436) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:17:02.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:17:02.323+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:02.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:17:02.339+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:02.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:17:02.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:17:02.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.051 seconds
[2025-01-17T11:17:32.861+0000] {processor.py:186} INFO - Started process (PID=2502) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:17:32.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:17:32.863+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:32.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:17:32.877+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:32.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:17:32.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:17:32.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-17T11:18:03.563+0000] {processor.py:186} INFO - Started process (PID=2568) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:18:03.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:18:03.565+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:03.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:18:03.579+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:03.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:18:03.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:18:03.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:18:34.077+0000] {processor.py:186} INFO - Started process (PID=2635) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:18:34.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:18:34.079+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:34.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:18:34.097+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:34.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:18:34.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:18:34.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-17T11:19:04.912+0000] {processor.py:186} INFO - Started process (PID=2701) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:19:04.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:19:04.914+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:04.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:19:04.928+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:04.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:19:04.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:19:04.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T11:19:35.277+0000] {processor.py:186} INFO - Started process (PID=2767) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:19:35.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:19:35.280+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:35.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:19:35.303+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:35.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:19:35.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:19:35.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.063 seconds
[2025-01-17T11:20:06.029+0000] {processor.py:186} INFO - Started process (PID=2833) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:20:06.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:20:06.031+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:06.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:20:06.046+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:06.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:20:06.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:20:06.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.054 seconds
[2025-01-17T11:20:36.220+0000] {processor.py:186} INFO - Started process (PID=2899) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:20:36.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:20:36.223+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:36.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:20:36.237+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:36.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:20:36.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:20:36.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:21:06.757+0000] {processor.py:186} INFO - Started process (PID=2965) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:21:06.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:21:06.760+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:06.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:21:06.775+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:06.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:21:06.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:21:06.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-17T11:21:37.165+0000] {processor.py:186} INFO - Started process (PID=3031) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:21:37.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:21:37.168+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:37.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:21:37.188+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:37.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:21:37.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:21:37.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T11:22:07.394+0000] {processor.py:186} INFO - Started process (PID=3098) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:22:07.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:22:07.396+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:07.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:22:07.410+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:07.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:22:07.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:22:07.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.035 seconds
[2025-01-17T11:22:38.045+0000] {processor.py:186} INFO - Started process (PID=3164) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:22:38.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:22:38.048+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:38.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:22:38.062+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:38.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:22:38.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:22:38.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T11:23:08.611+0000] {processor.py:186} INFO - Started process (PID=3230) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:23:08.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:23:08.614+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:08.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:23:08.628+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:08.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:23:08.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:23:08.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:23:38.757+0000] {processor.py:186} INFO - Started process (PID=3296) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:23:38.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:23:38.760+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:38.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:23:38.773+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:38.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:23:38.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:23:38.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:24:09.410+0000] {processor.py:186} INFO - Started process (PID=3362) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:24:09.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:24:09.412+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:09.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:24:09.426+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:09.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:24:09.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:24:09.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.036 seconds
[2025-01-17T11:24:40.318+0000] {processor.py:186} INFO - Started process (PID=3428) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:24:40.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:24:40.321+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:40.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:24:40.335+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:40.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:24:40.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:24:40.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-17T11:25:10.755+0000] {processor.py:186} INFO - Started process (PID=3494) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:25:10.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:25:10.758+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:10.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:25:10.772+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:10.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:25:10.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:25:10.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-17T11:25:41.133+0000] {processor.py:186} INFO - Started process (PID=3560) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:25:41.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:25:41.135+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:41.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:25:41.147+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:41.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:25:41.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:25:41.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T11:26:11.425+0000] {processor.py:186} INFO - Started process (PID=3626) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:26:11.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:26:11.427+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:11.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:26:11.441+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:11.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:26:11.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:26:11.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-17T11:26:41.509+0000] {processor.py:186} INFO - Started process (PID=3691) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:26:41.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:26:41.511+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:41.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:26:41.525+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:41.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:26:41.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:26:41.553+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:27:11.778+0000] {processor.py:186} INFO - Started process (PID=3757) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:27:11.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:27:11.781+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:11.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:27:11.802+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:11.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:27:11.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:27:11.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T11:27:42.317+0000] {processor.py:186} INFO - Started process (PID=3823) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:27:42.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:27:42.320+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:42.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:27:42.336+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:42.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:27:42.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:27:42.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.053 seconds
[2025-01-17T11:28:13.336+0000] {processor.py:186} INFO - Started process (PID=3889) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:28:13.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:28:13.338+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:13.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:28:13.351+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:13.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:28:13.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:28:13.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.036 seconds
[2025-01-17T11:28:43.708+0000] {processor.py:186} INFO - Started process (PID=3955) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:28:43.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:28:43.711+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:43.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:28:43.724+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:43.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:28:43.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:28:43.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:29:14.365+0000] {processor.py:186} INFO - Started process (PID=4022) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:29:14.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:29:14.367+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:14.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:29:14.382+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:14.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:29:14.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:29:14.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-17T11:29:44.792+0000] {processor.py:186} INFO - Started process (PID=4084) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:29:44.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:29:44.794+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:44.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:29:44.809+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:44.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:29:44.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:29:44.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-17T11:40:52.337+0000] {processor.py:186} INFO - Started process (PID=4147) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:40:52.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:40:52.339+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:40:52.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:40:52.358+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:40:52.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:40:52.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:40:52.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:41:23.046+0000] {processor.py:186} INFO - Started process (PID=4209) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:41:23.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:41:23.048+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:23.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:41:23.062+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:23.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:41:23.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:41:23.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:41:53.385+0000] {processor.py:186} INFO - Started process (PID=4275) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:41:53.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:41:53.387+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:53.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:41:53.402+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:53.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:41:53.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:41:53.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:42:23.751+0000] {processor.py:186} INFO - Started process (PID=4341) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:42:23.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:42:23.753+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:23.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:42:23.767+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:23.766+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:42:23.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:42:23.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:42:54.468+0000] {processor.py:186} INFO - Started process (PID=4407) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:42:54.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:42:54.470+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:54.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:42:54.483+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:54.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:42:54.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:42:54.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.035 seconds
[2025-01-17T11:43:24.807+0000] {processor.py:186} INFO - Started process (PID=4473) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:43:24.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:43:24.809+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:24.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:43:24.823+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:24.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:43:24.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:43:24.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:43:55.263+0000] {processor.py:186} INFO - Started process (PID=4539) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:43:55.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:43:55.265+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:55.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:43:55.278+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:55.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:43:55.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:43:55.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:44:25.759+0000] {processor.py:186} INFO - Started process (PID=4605) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:44:25.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:44:25.761+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:25.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:44:25.775+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:25.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:44:25.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:44:25.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T11:44:55.975+0000] {processor.py:186} INFO - Started process (PID=4671) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:44:55.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:44:55.977+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:55.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:44:55.993+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:55.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:44:55.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:44:56.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.041 seconds
[2025-01-17T11:45:26.657+0000] {processor.py:186} INFO - Started process (PID=4737) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:45:26.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:45:26.659+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:26.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:45:26.674+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:26.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:45:26.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:45:26.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:45:57.225+0000] {processor.py:186} INFO - Started process (PID=4803) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:45:57.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:45:57.227+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:57.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:45:57.241+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:57.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:45:57.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:45:57.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T11:46:27.383+0000] {processor.py:186} INFO - Started process (PID=4869) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:46:27.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:46:27.387+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:27.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:46:27.408+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:27.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:46:27.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:46:27.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.063 seconds
[2025-01-17T11:46:57.763+0000] {processor.py:186} INFO - Started process (PID=4935) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:46:57.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:46:57.765+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:57.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:46:57.780+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:57.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:46:57.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:46:57.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-17T11:47:28.154+0000] {processor.py:186} INFO - Started process (PID=5001) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:47:28.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:47:28.156+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:28.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:47:28.168+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:28.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:47:28.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:47:28.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-17T11:47:58.322+0000] {processor.py:186} INFO - Started process (PID=5067) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:47:58.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:47:58.324+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:58.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:47:58.338+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:58.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:47:58.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:47:58.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.038 seconds
[2025-01-17T11:48:28.675+0000] {processor.py:186} INFO - Started process (PID=5133) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:48:28.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:48:28.677+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:28.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:48:28.702+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:28.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:48:28.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:48:28.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.051 seconds
[2025-01-17T11:48:58.987+0000] {processor.py:186} INFO - Started process (PID=5199) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:48:58.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:48:58.989+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:58.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:48:59.007+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:59.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:48:59.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:48:59.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.057 seconds
[2025-01-17T11:49:29.439+0000] {processor.py:186} INFO - Started process (PID=5265) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:49:29.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T11:49:29.442+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:49:29.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:49:29.525+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:49:29.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T11:49:29.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T11:49:29.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.148 seconds
[2025-01-17T12:03:42.930+0000] {processor.py:186} INFO - Started process (PID=5279) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:03:42.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:03:42.933+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:03:42.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:03:42.949+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:03:42.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:03:42.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:03:42.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T12:04:13.104+0000] {processor.py:186} INFO - Started process (PID=5343) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:04:13.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:04:13.106+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:13.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:04:13.119+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:13.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:04:13.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:04:13.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.054 seconds
[2025-01-17T12:04:43.978+0000] {processor.py:186} INFO - Started process (PID=5409) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:04:43.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:04:43.979+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:43.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:04:43.993+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:43.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:04:43.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:04:44.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T12:05:14.142+0000] {processor.py:186} INFO - Started process (PID=5475) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:05:14.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:05:14.144+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:14.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:05:14.156+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:14.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:05:14.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:05:14.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.035 seconds
[2025-01-17T12:05:44.477+0000] {processor.py:186} INFO - Started process (PID=5541) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:05:44.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:05:44.479+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:44.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:05:44.493+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:44.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:05:44.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:05:44.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-17T12:06:14.753+0000] {processor.py:186} INFO - Started process (PID=5607) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:06:14.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:06:14.756+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:14.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:06:14.770+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:14.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:06:14.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:06:14.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T12:06:44.858+0000] {processor.py:186} INFO - Started process (PID=5673) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:06:44.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:06:44.860+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:44.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:06:44.873+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:44.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:06:44.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:06:44.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T12:07:15.314+0000] {processor.py:186} INFO - Started process (PID=5739) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:07:15.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:07:15.317+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:15.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:07:15.330+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:15.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:07:15.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:07:15.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T12:07:46.103+0000] {processor.py:186} INFO - Started process (PID=5805) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:07:46.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:07:46.105+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:46.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:07:46.119+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:46.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:07:46.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:07:46.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.036 seconds
[2025-01-17T12:08:16.975+0000] {processor.py:186} INFO - Started process (PID=5871) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:08:16.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:08:16.977+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:16.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:08:16.991+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:16.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:08:16.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:08:17.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T12:08:47.990+0000] {processor.py:186} INFO - Started process (PID=5937) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:08:47.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:08:47.992+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:47.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:08:48.008+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:48.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:08:48.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:08:48.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-17T12:09:19.013+0000] {processor.py:186} INFO - Started process (PID=6009) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:09:19.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:09:19.015+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:19.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:09:19.029+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:19.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:09:19.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:09:19.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T12:09:49.923+0000] {processor.py:186} INFO - Started process (PID=6075) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:09:49.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:09:49.925+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:49.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:09:49.939+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:49.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:09:49.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:09:49.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T12:10:20.403+0000] {processor.py:186} INFO - Started process (PID=6141) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:10:20.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:10:20.405+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:20.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:10:20.417+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:20.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:10:20.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:10:20.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.046 seconds
[2025-01-17T12:10:50.824+0000] {processor.py:186} INFO - Started process (PID=6207) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:10:50.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:10:50.827+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:50.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:10:50.848+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:50.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:10:50.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:10:50.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.059 seconds
[2025-01-17T12:11:21.295+0000] {processor.py:186} INFO - Started process (PID=6273) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:11:21.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:11:21.297+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:21.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:11:21.311+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:21.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:11:21.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:11:21.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T12:11:51.631+0000] {processor.py:186} INFO - Started process (PID=6339) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:11:51.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:11:51.633+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:51.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:11:51.651+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:51.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:11:51.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:11:51.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.043 seconds
[2025-01-17T12:12:22.364+0000] {processor.py:186} INFO - Started process (PID=6405) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:12:22.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:12:22.367+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:22.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:12:22.380+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:22.379+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:12:22.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:12:22.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.047 seconds
[2025-01-17T12:12:53.431+0000] {processor.py:186} INFO - Started process (PID=6471) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:12:53.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:12:53.433+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:53.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:12:53.447+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:53.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:12:53.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:12:53.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T12:13:24.077+0000] {processor.py:186} INFO - Started process (PID=6537) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:13:24.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:13:24.091+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:24.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:13:24.157+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:24.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:13:24.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:13:24.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.137 seconds
[2025-01-17T12:13:55.178+0000] {processor.py:186} INFO - Started process (PID=6603) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:13:55.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:13:55.180+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:55.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:13:55.197+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:55.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:13:55.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:13:55.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.042 seconds
[2025-01-17T12:14:25.295+0000] {processor.py:186} INFO - Started process (PID=6669) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:14:25.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:14:25.297+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:25.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:14:25.312+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:25.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:14:25.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:14:25.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.039 seconds
[2025-01-17T12:14:55.578+0000] {processor.py:186} INFO - Started process (PID=6735) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:14:55.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:14:55.580+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:55.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:14:55.593+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:55.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:14:55.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:14:55.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T12:15:26.650+0000] {processor.py:186} INFO - Started process (PID=6801) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:15:26.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:15:26.652+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:26.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:15:26.669+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:26.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:15:26.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:15:26.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.052 seconds
[2025-01-17T12:15:56.960+0000] {processor.py:186} INFO - Started process (PID=6867) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:15:56.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:15:56.962+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:56.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:15:56.978+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:56.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:15:56.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:15:57.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.049 seconds
[2025-01-17T12:16:27.829+0000] {processor.py:186} INFO - Started process (PID=6933) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:16:27.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:16:27.831+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:27.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:16:27.845+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:27.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:16:27.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:16:27.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.037 seconds
[2025-01-17T12:16:58.484+0000] {processor.py:186} INFO - Started process (PID=6999) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:16:58.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:16:58.487+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:58.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:16:58.507+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:58.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:16:58.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:16:58.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.059 seconds
[2025-01-17T12:17:29.266+0000] {processor.py:186} INFO - Started process (PID=7065) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:17:29.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:17:29.268+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:17:29.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:17:29.283+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:17:29.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:17:29.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:17:29.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.048 seconds
[2025-01-17T12:18:00.172+0000] {processor.py:186} INFO - Started process (PID=7131) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:18:00.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:18:00.174+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:00.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:18:00.190+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:00.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:18:00.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:18:00.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.050 seconds
[2025-01-17T12:18:30.539+0000] {processor.py:186} INFO - Started process (PID=7197) to work on /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:18:30.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/CapstoneETL.py for tasks to queue
[2025-01-17T12:18:30.546+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:30.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:18:30.578+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:30.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/CapstoneETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/CapstoneETL.py", line 132
    %pip install psycopg2
    ^
SyntaxError: invalid syntax
[2025-01-17T12:18:30.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/CapstoneETL.py
[2025-01-17T12:18:30.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/CapstoneETL.py took 0.154 seconds
